### ISSUE TITLE
Demo Folder?

### ISSUE THREAD

**Issue by alexcurtin** [Shopify/kubernetes-deploy#158]
Hi Shopify,

I am trying to get started using this tool but would love an example or demo folder with sample app, template and template erb to hit the ground running. Is this something that exists in another repo?

**Comment by Raffo** [comment]
+1 on this, it's kind of hard to figure out how to do it without a demo folder, especially multi-environments setup (test, prod for example).

**Comment by KnVerey** [comment]
@Raffo did you have a chance to take a look at our `test/fixtures/hello-cloud` template set as suggested above? It's basically a sample app with a wide variety of simple resources using publicly available images. We could mention that in our readme if it is useful; otherwise I'd be interested to know more specifics on what you need help with. 😃 

Re: multi-environment, `kubernetes-deploy` doesn't really have an opinion so long as you end up with a single directory of configuration files for it to process. One strategy we use internally is to store common files in one place and use symlinks to include them in the actual deploy directories. kubernetes-deploy provides ERB templating as a convenience, but our focus is on improving the deploy experience rather than the template management story. Since we are based on plain Kubernetes configuration files, we're highly composable with other tooling in the ecosystem that focuses on solutions for generating those files from other/simpler formats.

**Comment by Raffo** [comment]
Thanks for the answer! 

I took a look and the folder is actually quite helpful, I think that I link in the README would be a good addition. 

I was looking for a full solution for multiple environments so I expected to see multiple folders and more "composable" or complex examples. For example, even a folder with simlinks or just additional documentation would have helped me figure out the details around multiple environments setup (I am still unsure if simlinks would be right for my case, but that's another story 😄 ).

**Comment by KnVerey** [comment]
Added this to our generic documentation issue: https://github.com/Shopify/kubernetes-deploy/issues/105
