### ISSUE TITLE
Better error when the kube config has the wrong master IP

### ISSUE THREAD

**Issue by stefanmb** [Shopify/kubernetes-deploy#164]
Currently seeing:

```
[INFO][2017-09-11 20:25:03 +0000]	
[INFO][2017-09-11 20:25:03 +0000]	------------------------------------Phase 1: Initializing deploy------------------------------------
[INFO][2017-09-11 20:25:03 +0000]	All required parameters and files are present
[INFO][2017-09-11 20:25:03 +0000]	Context pipa-test found
[INFO][2017-09-11 20:25:34 +0000]	
[INFO][2017-09-11 20:25:34 +0000]	------------------------------------------Result: FAILURE-------------------------------------------
[FATAL][2017-09-11 20:25:34 +0000]	Namespace pipa-test not found
```

This is a bit confusing to users since it says "Context pipa-test found" which seems to refer to the kube config file, but the actual error occurs at the namespace lookup.

**Comment by KnVerey** [comment]
I think this happens because the context check doesn't actually try to hit the server (just looks for a name in the kubeconfig), making the namespace check the first thing that does. We could fix https://github.com/Shopify/kubernetes-deploy/issues/152 at the same time by changing the context check to a validation that requests the target server version.

**Comment by KnVerey** [comment]
We've also seen namespace not found errors when the namespace actually exists but there was an error in requesting it. We should be more careful about the error returned by kubectl in this validation and retry it if appropriate.

**Comment by KnVerey** [comment]
Fixed by https://github.com/Shopify/kubernetes-deploy/pull/190. The namespace check is no longer the first API call, and both the server validation and the namespace check are now retried.
