### ISSUE TITLE
[Query] Namespace requirement

### ISSUE THREAD

**Issue by sarge** [Shopify/kubernetes-deploy#300]
Hi all,

I am trying to understand the intention and impact of the sentence "Each app managed by kubernetes-deploy must have its own exclusive Kubernetes namespace."

What does app mean in this context? I am assuming a set of heterogeneous pods?

What happens if 2 apps were to occupy the same namespace?

Many thanks

Mark

**Comment by dturn** [comment]
Hi @sarge,

For more information on namespaces take a look at this document: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces . Kubernetes-deploy requires each app to have its own namespace so that it can prune resources that you want deleted. More information about pruning can be found here: https://kubernetes.io/docs/concepts/overview/object-management-kubectl/declarative-config/


Please let me know if you have more questions, and thanks for checking out our tool.

-Danny

**Comment by sarge** [comment]
Thanks @dturn 

Every tool has its management philosophy. I see it is the pruning feature that needs to understand the scope of resources that is allowed to clean up.
Kubernetes-Deploy is repository centric, so we could say that each application gets its own repository and thus needs it's own namespace.

Thanks again

Mark
