### ISSUE TITLE
Recommended approach for running `rails console` or rolling back?

### ISSUE THREAD

**Issue by ramontayag** [Shopify/kubernetes-deploy#302]
This is neither a bug report or feature request, but I don't know where else to ask.

What is the recommended approach for running things like `rails console` or `rails db:rollback`? I was looking at the task-runner, but it seems that it isn't meant to be deploying a specific version of the app, but rather be a container running a more generic environment to do general tasks.

**Comment by dturn** [comment]
I don't know that we have a recommended approach for either but there are options.

 If you can't exec into a running container (e.g it crashes on boot and the logs aren't providing enough information to debug). One option would be to create a pod with your app image, but change the command to `["sleep", "8000"]`.  You could then exec into the sleeping container to run `rails console`.

**Comment by KnVerey** [comment]
Re: `rails console`, this gem doesn't including any tools for running _interactive_ commands, but I agree with Danny that the usual approach is to deploy a long-running pod with your app image and `kubectl exec` into it.

Re: `rails db:rollback`, although I haven't tried it for this purpose myself, I think [kubernetes-run](https://github.com/Shopify/kubernetes-deploy#kubernetes-run) should work for something like that. Basically, you include a pod template that uses your app image in your regular deploy (so that it always references the latest image), and then the command to launch a rollback pod from that template would be something like `kubernetes-run $namespace $context bundle exec rails db:rollback` (the exact command depends on the structure of your image).

**Comment by ramontayag** [comment]
Ok, thank you for the recommendations! Will check out how to implement rollback using `kubernetes-run`.

**Comment by yfxie** [comment]
For anyone finding this later: I wrote kran, a thin wrapper around krane, and it covers the console side of this. `kran console` runs `kubectl exec -it` into an app pod picked by a label selector from config/kran.yml, and `kran exec bin/rails db:rollback` runs a one-off command in a pod the same way. Nothing kubectl can't already do, just fewer flags to remember each time.

https://github.com/yfxie/kran
