### ISSUE TITLE
Get kubernetes-deploy 1.11 CI working

### ISSUE THREAD

**Issue by randy-abson** [Shopify/kubernetes-deploy#331]
Required to add support for k8s 1.11

**Comment by dturn** [comment]
The tests pass locally for me against 1.11. So this issue is about adding it to our CI / nightly builds and any fixup that requires (🤞 none). Ideally we'd complete https://github.com/Shopify/kubernetes-deploy/issues/332 first so that we can use the latest build infrastructure. But it would be acceptable to use the current infrastructure if gke makes 1.11 and #332 isn't finished.

**Comment by KnVerey** [comment]
IMO yes, it would be acceptable to use the current infrastructure if we don't have #332 ready in time.

**Comment by karanthukral** [comment]
@dturn I seem to have 1 test failing consistently when I run minikube 1.11 locally. the test is `test_failure_logs_from_unmanaged_pod_appear_in_summary_section` and its due to the `SuccessfulMountVolume` event never firing. Looking at the minikube logs, seems like the `VerifyControllerAttachedVolume` call is immediately followed by `UnmountVolume` which is why the event isn't fired. I haven't tested this on the kubeadm stuff so it remains to be seen if there are any issues there.

I assume the tests just worked on your end?

**Comment by karanthukral** [comment]
That ends up being only one of the failing tests on 1.11 CI with kubeadm as seen in this [build](https://buildkite.com/shopify/kubernetes-deploy-gem/builds/983#e8d5017a-d729-408a-8f8e-e9607f64c566). I am looking into seeing why they might be failing but might need help 👍

**Comment by karanthukral** [comment]
Just merged it
