### ISSUE TITLE
Make setting ENV["REVISION"] optional

### ISSUE THREAD

**Issue by KnVerey** [Shopify/kubernetes-deploy#351]
We are using this to:
- Set the value of `current_sha` in the ERB renderer
- Generate a `deployment_id`, also in the renderer
- Tag statsD metrics with this value

None of that is really necessary to deploy, and indeed some projects do not use revision-based deploys so this is forcing them to set a dummy value. Let's make this optional.

**Comment by benlangfeld** [comment]
What do you think of additionally making it possible to pass this as an option rather than an environment variable? My use case is running kubernetes-deploy inside a generic container full of tools with a wrapper script which invokes `docker run`, but I don't want to infect the wrapper script with knowledge of kubernetes-deploy by doing `docker run --env REVISION`.

**Comment by KnVerey** [comment]
@benlangfeld in that scenario wouldn't it work to inline the env var at the invocation site, like `REVISION=abc kubernetes-deploy ...`?

**Comment by benlangfeld** [comment]
@KnVerey No. I have a wrapper script something like this:

```bash
#!/bin/bash

set -e

VERSION=${VERSION:-"latest"}
TILLER_NAMESPACE=${TILLER_NAMESPACE:-"app-tiller"}
IMAGE="some-image:$VERSION"

if [ -t 0 ]; then
  INTERACTIVE="--interactive"
fi

docker run \
  $INTERACTIVE --tty --rm \
  --env CONTEXT \
  --env TILLER_NAMESPACE=$TILLER_NAMESPACE \
  --mount type=bind,source="$HOME/.aws/credentials",destination=/root/.aws/credentials,readonly \
  --mount type=bind,source="$HOME/.kube",destination=/root/.kube \
  --mount type=bind,source="$(pwd)",destination=/app \
  $IMAGE bash --login -c "$*"
```

The container image referenced here contains tools such as kubectl, helm, stern, kubernetes-deploy etc. It is a way for our platform team to deliver an approved set of tools with a controlled upgrade procedure to our application teams.

Application developers invoke kubernetes-deploy as: `app kubernetes-deploy ...`, much as they invoke kubectl as `app kubectl --namespace foo get pods`. In order to pass `REVISION` through, I would need to do `--env REVISION` here, but that is putting knowledge of kubernetes-deploy into this wrapper script, which I would like to avoid. I would like to be able to invoke it as `app kubernetes-deploy --revision abc ...` instead.
