### ISSUE TITLE
DB migration runs before launching DB instance

### ISSUE THREAD

**Issue by yfxie** [Shopify/kubernetes-deploy#399]
I followed the section `Running tasks at the beginning of a deploy` to do DB migration and my database is `self-hosting` instead of using RDS/Google SQL. my DB migration pod cant connects to DB, because of the orders of objects creation.

the issue scenario case like following:
1. [pvc]db-storage
2. [pod]db-migration
3. [deployment]app-deployment
4. [deployment]pg-deployment

if the orders of them are `db-storage->pg-deployment->db-migration->app-deployment`, everything will be fine.

any suggestion? can pg-deployment run before pod by any way?

**Comment by yfxie** [comment]
issue solved by workaround: 
1. deploy without db-migration pod first
2. pg-deployment is created
3. deploy again with db-migration
this issue probably only happen when the first deployment.

**Comment by KnVerey** [comment]
Hi @yfxie! To answer your question, it is not currently possible to customize the deploy sequence. We have not run into this problem ourselves because our databases are driven by custom resources and do not run inside the Kubernetes namespace. You're right that this problem should only occur on the first deploy, but we've taken note of this issue.
