### ISSUE TITLE
Update kubeclient

### ISSUE THREAD

**Issue by KnVerey** [Shopify/kubernetes-deploy#406]
Related to #396 -- the most recent release should be compatible with AWS.

Our "google-friendly" patch might also be obsolete at this point. We should read the changelog and confirm.

**Comment by timothysmith0609** [comment]
If I'm not mistaken we'll still need to override `Kubeclient::Config#fetch_user_auth_options` since otherwise there's no way to know which auth provider is required for a given context object. It looks like core kubeclient [already handles AWS](https://github.com/abonas/kubeclient/blob/master/lib/kubeclient/config.rb#L152) (via `user.key?('exec'), see #396 ). 

This is particularly annoying with cloud-portal, where we sometimes want to use our user credentials to target actual GCP clusters in development instead of our local minikube environment via `$LOCAL_CONTEXT`. The ability to check for this case is hidden behind the kubeclient interface so overriding is really our only choice at the moment.
